name: Contribution Snake

on:
  push:  
    branches:
      - "breadrock1-patch-2"
#   schedule:
#     - cron: "0 */24 * * *" # every 24 hours
#   workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
#       - name: Generate
#         uses: Platane/snk@master
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs:
#             dist/github-snake.svg
#             dist/github-snake-dark.svg?palette=github-dark
#             dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

#       - name: Push
#         uses: crazy-max/ghaction-github-pages@v2.5.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
