name: Contribution Snake

on:
  push: master
  schedule:
    - cron: "0 */24 * * *" # every 24 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate
        uses: Platane/snk@master
        with:
          github_user_name: breadrock1
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
